

  ========= 测试开始 : 20230212_173028 =========



>>> cases\API_自动化测试用例\空白环境\

[ suite setup ] cases\API_自动化测试用例\空白环境\
suite_setup

-- 第 1 步 -- 清空所有学生/老师/班级 



>>> cases\API_自动化测试用例\空白环境\blank_test.py

* 添加班级1  -  2023-02-12 17:30:28

  [ case execution steps ]

-- 第 1 步 -- 添加班级 

接口返回0

** 检查点 **  检查返回值 ---->  通过

接口返回20762

** 检查点 **  检查返回值 ---->  通过

  PASS 


>>> cases\API_自动化测试用例\空白环境\存在班级\

[ suite setup ] cases\API_自动化测试用例\空白环境\存在班级\

-- 第 1 步 -- 添加班级 

old初始班级id:20763


>>> cases\API_自动化测试用例\空白环境\存在班级\excl_class.py

* 添加班级2  -  2023-02-12 17:30:28

  [ case execution steps ]

-- 第 1 步 -- 添加班级 

接口返回{'invitecode': '207649006385', 'retcode': 0, 'id': 20764}
接口返回0

** 检查点 **  检查返回值 ---->  通过

接口返回20764

** 检查点 **  检查返回结果 ---->  通过

  PASS 

* 添加班级3  -  2023-02-12 17:30:28

  [ case execution steps ]

-- 第 1 步 -- 添加相同名称的班级 

接口返回{'reason': 'Traceback (most recent call last):\n  File "/home/yjyx/yijiao_src/yijiao_main/services/datamodel/schoolclass/models.py", line 542, in addClass\n    school_class = self._addClass(name,schoolid,gradeid,studentlimit)\n  File "/home/yjyx/yijiao_src/yijiao_main/services/datamodel/schoolclass/models.py", line 531, in _addClass\n    school_class.save()\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save\n    force_update=force_update, update_fields=update_fields)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert\n    using=using, raw=raw)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert\n    return query.get_compiler(using=using).execute_sql(return_id)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql\n    cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute\n    return self.cursor.execute(query, args)\n  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nIntegrityError: (1062, "Duplicate entry \'\\xe5\\x88\\x9d\\xe5\\xa7\\x8b\\xe7\\x8f\\xad\\xe7\\xba\\xa7-407-1\' for key \'name\'")\n', 'retcode': 1}
接口返回Traceback (most recent call last):
  File "/home/yjyx/yijiao_src/yijiao_main/services/datamodel/schoolclass/models.py", line 542, in addClass
    school_class = self._addClass(name,schoolid,gradeid,studentlimit)
  File "/home/yjyx/yijiao_src/yijiao_main/services/datamodel/schoolclass/models.py", line 531, in _addClass
    school_class.save()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '\xe5\x88\x9d\xe5\xa7\x8b\xe7\x8f\xad\xe7\xba\xa7-407-1' for key 'name'")


** 检查点 **  检查返回结果 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "cases\API_自动化测试用例\空白环境\存在班级\excl_class.py", line 35, in teststeps
    CHECK_POINT('检查返回结果', reason == 'duplicated class name')
  File "D:\Python39\lib\site-packages\hytest\common.py", line 58, in CHECK_POINT
    raise AssertionError()
AssertionError


* 修改班级1  -  2023-02-12 17:30:28

  [ case execution steps ]

-- 第 1 步 -- 修改班级名字 


-- 第 2 步 -- 查询班级名称 


** 检查点 **  检查返回结果 ---->  通过

  PASS 

* 修改班级2  -  2023-02-12 17:30:28

  [ case execution steps ]

-- 第 1 步 -- 创建班级 

添加班级id:20766
班级列表:{'gradeid': 1, 'retlist': [{'name': '测试001', 'grade__name': '七年级', 'invitecode': '207621674865', 'studentlimit': 100, 'studentnumber': 0, 'id': 20762, 'teacherlist': []}, {'name': '修改名称1676194228.7371202', 'grade__name': '七年级', 'invitecode': '207636582418', 'studentlimit': 100, 'studentnumber': 0, 'id': 20763, 'teacherlist': []}, {'name': '测试002', 'grade__name': '七年级', 'invitecode': '207649006385', 'studentlimit': 100, 'studentnumber': 0, 'id': 20764, 'teacherlist': []}, {'name': "<class 'excl_class.tc000052'>", 'grade__name': '七年级', 'invitecode': '207664941223', 'studentlimit': 100, 'studentnumber': 0, 'id': 20766, 'teacherlist': []}], 'retcode': 0}
班级列表:[{'name': '测试001', 'grade__name': '七年级', 'invitecode': '207621674865', 'studentlimit': 100, 'studentnumber': 0, 'id': 20762, 'teacherlist': []}, {'name': '修改名称1676194228.7371202', 'grade__name': '七年级', 'invitecode': '207636582418', 'studentlimit': 100, 'studentnumber': 0, 'id': 20763, 'teacherlist': []}, {'name': '测试002', 'grade__name': '七年级', 'invitecode': '207649006385', 'studentlimit': 100, 'studentnumber': 0, 'id': 20764, 'teacherlist': []}, {'name': "<class 'excl_class.tc000052'>", 'grade__name': '七年级', 'invitecode': '207664941223', 'studentlimit': 100, 'studentnumber': 0, 'id': 20766, 'teacherlist': []}]
班级列表:修改名称1676194228.7371202
修改返回结果:{'reason': '未知错误:Traceback (most recent call last):\n  File "/home/yjyx/yijiao_src/yijiao_main/services/datamodel/schoolclass/models.py", line 612, in modifyClass\n    school_class.save()\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save\n    force_update=force_update, update_fields=update_fields)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 803, in _save_table\n    forced_update)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 853, in _do_update\n    return filtered._update(values) > 0\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update\n    return query.get_compiler(self.db).execute_sql(CURSOR)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql\n    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql\n    cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute\n    return self.cursor.execute(query, args)\n  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nIntegrityError: (1062, "Duplicate entry \'\\xe4\\xbf\\xae\\xe6\\x94\\xb9\\xe5\\x90\\x8d\\xe7\\xa7\\xb01676194228.7371202-407-1\' for key \'name\'")\n', 'retcode': 10000}

** 检查点 **  检查返回结果 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "cases\API_自动化测试用例\空白环境\存在班级\excl_class.py", line 73, in teststeps
    CHECK_POINT('检查返回结果', reason == 'duplicated class name')
  File "D:\Python39\lib\site-packages\hytest\common.py", line 58, in CHECK_POINT
    raise AssertionError()
AssertionError


* 修改班级3  -  2023-02-12 17:30:28

  [ case execution steps ]

-- 第 1 步 -- 修改不存在的班级 

修改返回结果:{'reason': 'id 为`99999999`的班级不存在', 'retcode': 404}

** 检查点 **  检查返回结果 ---->  通过

  PASS 

* 删除班级1  -  2023-02-12 17:30:28

  [ case execution steps ]

-- 第 1 步 -- 删除不存在的班级 

修改返回结果:{'reason': 'id 为`9999999`的班级不存在', 'retcode': 404}

** 检查点 **  检查返回结果 ---->  通过

  PASS 

* 删除班级2  -  2023-02-12 17:30:28

[ case setup ] 删除班级2

-- 第 1 步 -- 创建班级 


  [ case execution steps ]

-- 第 2 步 -- 删除班级 

修改返回结果:{'retcode': 0}

** 检查点 **  检查返回结果 ---->  通过

  PASS 


>>> cases\API_自动化测试用例\空白环境\存在班级\excl_teacher.py

* 添加老师1  -  2023-02-12 17:30:29

  [ case execution steps ]

-- 第 1 步 -- 添加老师 

返回结果{'retcode': 0, 'id': 5402}

** 检查点 **  存在添加的老师 ---->  通过

  PASS 


>>> cases\API_自动化测试用例\空白环境\存在班级\存在老师\

[ suite setup ] cases\API_自动化测试用例\空白环境\存在班级\存在老师\

-- 第 1 步 -- 添加老师 

请求结果{'retcode': 0, 'id': 5403}
请求结果5403


>>> cases\API_自动化测试用例\空白环境\存在班级\存在老师\exte_student.py

* 添加学生1  -  2023-02-12 17:30:29

  [ case execution steps ]

-- 第 1 步 -- 添加学生 

返回结果{'retcode': 0, 'id': 2294}

** 检查点 **  添加成功 ---->  通过

返回结果{'retlist': [{'classid': 20763, 'realname': '测试学生', 'username': '测试学生', 'phonenumber': '13212390654', 'id': 2294}], 'retcode': 0}

** 检查点 **  是否添加成功 ---->  通过

  PASS 


>>> cases\API_自动化测试用例\空白环境\存在班级\存在老师\exte_teacher.py

* 添加老师2  -  2023-02-12 17:30:29

  [ case execution steps ]

-- 第 1 步 -- 添加老师 

接口返回{'retcode': 0, 'id': 5404}
返回结果{'retlist': [{'username': '登录1676194228', 'teachclasslist': [20763], 'realname': '测试老师', 'id': 5402, 'phonenumber': '1325090842', 'email': 'ceshi@16553.com', 'idcardnumber': '111111155'}, {'username': '初始老师', 'teachclasslist': [20763], 'realname': '测试老师', 'id': 5403, 'phonenumber': '13223646453', 'email': 'ceshi@16553.com', 'idcardnumber': '111111155'}, {'username': 'tc001009', 'teachclasslist': [20763], 'realname': '测试老师', 'id': 5404, 'phonenumber': '13248458874', 'email': 'ceshi@16553.com', 'idcardnumber': '111111155'}], 'retcode': 0}
5402
5403
5404

** 检查点 **  是否添加成功 ---->  通过

  PASS 

* 添加老师3  -  2023-02-12 17:30:29

  [ case execution steps ]

-- 第 1 步 -- 添加老师 

返回结果{'reason': '登录名 初始老师 已经存在', 'retcode': 1}

** 检查点 **  登录名 初始老师 已经存在 ---->  通过

  PASS 

* 修改老师1  -  2023-02-12 17:30:29

  [ case execution steps ]

-- 第 1 步 -- 修改老师 

返回结果{'reason': 'id 为`999999`的老师不存在', 'retcode': 1}

** 检查点 **   id 为`999999`的老师不存在 ---->  通过

  PASS 

* 修改老师2  -  2023-02-12 17:30:29

[ case setup ] 修改老师2

-- 第 1 步 -- 创建班级class2 

接口返回{'invitecode': '207688154807', 'retcode': 0, 'id': 20768}

  [ case execution steps ]

-- 第 1 步 -- 修改老师 

返回结果{'retcode': 0}

** 检查点 **  检查返回结果 ---->  通过

  PASS 

* 删除老师1  -  2023-02-12 17:30:29

  [ case execution steps ]

-- 第 1 步 -- 删除老师 

返回结果{'reason': 'id 为`9999999`的老师不存在', 'retcode': 404}

** 检查点 **  id 为`9999999`的老师不存在 ---->  通过

  PASS 

* 删除老师2  -  2023-02-12 17:30:29

[ case setup ] 删除老师2

-- 第 1 步 -- 添加老师 

返回结果{'retcode': 0, 'id': 5405}

  [ case execution steps ]

-- 第 2 步 -- 删除老师 

返回结果{'retcode': 0}

** 检查点 **  删除老师是否成功 ---->  通过


** 检查点 **  删除成功 ---->  通过


** 检查点 **  删除成功 ---->  通过


** 检查点 **  删除成功 ---->  通过

  PASS 


>>> cases\API_自动化测试用例\空白环境\存在班级\存在老师\存在学生\

[ suite setup ] cases\API_自动化测试用例\空白环境\存在班级\存在老师\存在学生\

-- 第 1 步 -- 添加学生 

返回结果{'retcode': 0, 'id': 2295}


>>> cases\API_自动化测试用例\空白环境\存在班级\存在老师\存在学生\exst_student.py

* 添加学生2  -  2023-02-12 17:30:29

  [ case execution steps ]

-- 第 1 步 -- 添加学生 

返回结果{'retcode': 0, 'id': 2296}
返回结果{'retlist': [{'classid': 20763, 'realname': '测试学生', 'username': '测试学生', 'phonenumber': '13212390654', 'id': 2294}, {'classid': 20763, 'realname': '初始学生', 'username': '初始学生', 'phonenumber': '13206391582', 'id': 2295}, {'classid': 20763, 'realname': '测试学生', 'username': 'tc002001', 'phonenumber': '13204987536', 'id': 2296}], 'retcode': 0}

** 检查点 **  是否添加成功 ---->  通过

  PASS 

* 删除学生1  -  2023-02-12 17:30:29

[ case setup ] 删除学生1

-- 第 1 步 -- 添加学生 


  [ case execution steps ]

-- 第 2 步 -- 删除学生 

返回结果{'retlist': [{'classid': 20763, 'realname': '测试学生', 'username': '测试学生', 'phonenumber': '13212390654', 'id': 2294}, {'classid': 20763, 'realname': '初始学生', 'username': '初始学生', 'phonenumber': '13206391582', 'id': 2295}, {'classid': 20763, 'realname': '测试学生', 'username': 'tc002001', 'phonenumber': '13204987536', 'id': 2296}], 'retcode': 0}

** 检查点 **  是否删除成功 ---->  通过

  PASS 


  ========= 测试结束 : 20230212_173029 =========


  耗时    : 1.736 秒


  预备执行用例数量 : 18

  实际执行用例数量 : 18

  通过 : 16

  失败 : 2

  异常 : 0

  套件初始化失败 : 0

  套件清除  失败 : 0

  用例初始化失败 : 0

  用例清除  失败 : 0
